name: OIDC Actions

on:
  pull_request:
    types:
      - opened
      - synchronize


permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.OJIVERSE_GOOGLECLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-actions-oidc-provider"
          service_account: 'github-actions@${{ secrets.OJIVERSE_GOOGLECLOUD_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Test
        run: gcloud iam service-accounts list